name: Go
on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
